# Dataset
train_db_name: VOCSegmentation
train_db_kwargs:
   split: trainaug
   batch_size: 16
val_db_name: VOCSegmentation
val_db_kwargs:
   batch_size: 16
num_workers: 4

# Model
backbone: 'resnet50'
model_kwargs:
  state_dict: /path/to/moco-state-dict/ 

# Optimizer
epochs: 45
scheduler: step
scheduler_kwargs:
   lr_decay_rate: 0.1
   lr_decay_epochs: [30, 40]

optimizer: sgd 
optimizer_kwargs:
   lr: 0.003
   weight_decay: 0.0001
   momentum: 0.9
   nesterov: False
